# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/baize-root";
    fsType = "btrfs";
    options = [
      "subvol=@root"
      "compress=zstd:3"
      "noatime"
      "discard=async"
    ];
  };

  fileSystems."/nix/store" = {
    device = "/dev/disk/by-label/baize-root";
    fsType = "btrfs";
    options = [
      "subvol=@nix-store"
      "compress=zstd:9"
      "noatime"
      "discard=async"
    ];
    neededForBoot = true;
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-label/baize-root";
    fsType = "btrfs";
    options = [
      "subvol=@var-log"
      "compress=zstd:3"
      "noatime"
      "discard=async"
    ];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-label/baize-root";
    fsType = "btrfs";
    options = [
      "subvol=@var-cache"
      "compress=zstd:3"
      "noatime"
      "discard=async"
    ];
  };

  fileSystems."/home/rivers/.cache" = {
    device = "/dev/disk/by-label/baize-root";
    fsType = "btrfs";
    options = [
      "subvol=@home-rivers-cache"
      "compress=zstd:3"
      "noatime"
      "discard=async"
    ];
  };

  fileSystems."/mnt/games" = {
    device = "/dev/disk/by-label/zhitai-games";
    fsType = "btrfs";
    options = [
      "compress=zstd:6"
      "noatime"
      "discard=async"
      "nofail"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/baize-boot";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  system.activationScripts.btrfsCompressionProperties.text = ''
    set_btrfs_compression() {
      path="$1"
      compression="$2"

      if ${pkgs.util-linux}/bin/findmnt -T "$path" -n -o FSTYPE | ${pkgs.gnugrep}/bin/grep -qx btrfs; then
        current="$(${pkgs.btrfs-progs}/bin/btrfs property get "$path" compression 2>/dev/null | ${pkgs.gnused}/bin/sed 's/^compression=//')"
        if [ "$current" != "$compression" ]; then
          ${pkgs.btrfs-progs}/bin/btrfs property set "$path" compression "$compression" 2>/dev/null || true
        fi
      fi
    }

    set_btrfs_compression / zstd:3
    set_btrfs_compression /nix/store zstd:9
    set_btrfs_compression /var/log zstd:3
    set_btrfs_compression /var/cache zstd:3
    set_btrfs_compression /home/rivers/.cache zstd:3
    set_btrfs_compression /mnt/games zstd:6
  '';

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
