font=Noto Sans CJK SC 11
width=320
height=150
margin=10
padding=14
border-size=1
border-radius=10
background-color=#fffaf0b8
text-color=#353b40
border-color=#fffdf5b0
progress-color=over #c8bba9a0
anchor=top-right
layer=overlay
default-timeout=6000
max-visible=3
max-history=50
group-by=none
format=<b>%s</b>\n%b

[urgency=critical]
default-timeout=0
border-color=#c78c7c

[mode=do-not-disturb]
invisible=1
